name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: ghsync-linux-x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: ghsync-macos-x86_64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: ghsync-macos-arm64

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

    - name: Run tests
      run: cargo test --verbose

    - name: Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: target/${{ matrix.target }}/release/ghsync

  release:
    if: github.event_name == 'release'
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create release assets
      run: |
        chmod +x ghsync-linux-x86_64/ghsync
        tar -czf ghsync-linux-x86_64.tar.gz -C ghsync-linux-x86_64 ghsync
        
        chmod +x ghsync-macos-x86_64/ghsync
        tar -czf ghsync-macos-x86_64.tar.gz -C ghsync-macos-x86_64 ghsync
        
        chmod +x ghsync-macos-arm64/ghsync
        tar -czf ghsync-macos-arm64.tar.gz -C ghsync-macos-arm64 ghsync

    - name: Upload release assets
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ghsync-linux-x86_64.tar.gz
          ghsync-macos-x86_64.tar.gz
          ghsync-macos-arm64.tar.gz